### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by AlAskalany**

### CODE REVIEW

**Review by blagicaz — DISMISSED** [review]

**Review by fongv1 — DISMISSED** [review]
lgtm

**Comment by AlAskalany** [comment]
Resolved the conflicts.

**Review by FatemehEngqvist — APPROVED** [review]
Awesome!

**Comment by AlAskalany** [comment]
@FatemehEngqvist Thanks for the approval!

**Review by fongv1 — APPROVED** [review]
lgtm

**Pull request merged**
